Repository Wingle-SMWU/Wingle-Frontend, pull requests merged in 2023-07, with the labels that each got.

#76 Style/mobile responsive [커뮤니티]
  src/components/ui/NoDataUI.tsx
  src/pages/_app.tsx
Labels: ✍️ Desgin

#77 Style/community 기능 QA
  src/components/community/detail/body.tsx
  src/components/community/detail/comment.tsx
  src/components/community/detail/commentInput.tsx
  src/components/community/detail/profile.tsx
  src/pages/community/create.tsx
Labels: ✍️ Desgin

#82 style : mypage - 모바일 반영
  src/components/mypage/Profile.tsx
  src/components/mypage/countryDropDown.tsx
  src/pages/mypage/edit/index.tsx
  src/pages/mypage/edit/introduce.tsx
  src/pages/mypage/edit/language.tsx
  src/pages/mypage/edit/nickname.tsx
  src/pages/mypage/index.tsx
Labels: ✍️ Desgin

#91 Design/90 message qa
  src/components/messageComp/msgInput.tsx
  src/components/messageComp/msgList.tsx
  src/components/messageComp/receptionMsg.tsx
  src/components/messageComp/sendMsg.tsx
  src/pages/messages/[roomId]/index.tsx
  src/pages/profile/index.tsx
Labels: ✍️ Desgin

#100 feat: univLabel 공통 UI 제작
  src/components/community/list/listCard.tsx
  src/components/ui/univLabel.tsx
  src/types/community/article.d.ts
Labels: ✨ Feature, ✍️ Desgin

#102 Feature/auth with university
  src/api/auth/signUpApi.ts
  src/atoms/auth/signUpAtoms.ts
  src/components/authpage/signup/agreeBox.tsx
  src/components/authpage/signup/agreementComponent.tsx
  src/components/authpage/signup/dropDownSignUpCountry.tsx
  src/components/authpage/signup/signUpInput/index.tsx
  src/components/authpage/signup/signUpInput/inputUnivDropdown.tsx
  src/components/authpage/signup/studentCard.tsx
  src/components/ui/dropDownUI.tsx
  src/constants/countryList.ts
  src/constants/universityList.ts
  src/hooks/useRedirectToMain.ts
  src/pages/auth/signup.tsx
  src/types/auth/signupFormDataType.ts
Labels: ✨ Feature, 📬 API, ✍️ Desgin

#113 Feature/112 mypage language
  src/atoms/profileStateAtom.ts
  src/components/mypage/Profile.tsx
  src/components/ui/univLabel.tsx
  src/pages/mypage/edit/language.tsx
  src/pages/profile/index.tsx
  src/types/mypage/profileType.ts
Labels: ✨ Feature, 🚂 Refactor
