Repository Wingle-SMWU/Wingle-Frontend, pull requests merged in 2023-05, with the labels that each got.

#45 feature/43-mypage-api
  public/mypage/female.svg
  public/mypage/language1.svg
  public/mypage/language2.svg
  public/mypage/language3.svg
  public/mypage/male.svg
  src/api/axiosModule.ts
  src/api/mypage/profileData.ts
  src/atoms/profileStateAtom.ts
  src/components/authpage/signup/dropDown.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/SelectInterest.tsx
  src/components/mypage/selectLanguage.tsx
  src/components/ui/loadingUI.tsx
  src/constants/countryList.ts
  src/pages/mypage/edit/index.tsx
  src/pages/mypage/edit/interest.tsx
  src/pages/mypage/edit/introduce.tsx
  src/pages/mypage/edit/language.tsx
  src/pages/mypage/edit/nickname.tsx
  src/pages/mypage/index.tsx
  src/types/mypage/profileType.ts
Labels: ✨ Feature, 📬 API

#51 Feature/39 message api
  public/images/message/profiledefault.png
  src/api/message/messageApi.ts
  src/atoms/temp.ts
  src/components/Message/MsgInput.tsx
  src/components/Message/MsgList.tsx
  src/components/Message/ReceptionMsg.tsx
  src/components/Message/SendMsg.tsx
  src/components/Message/YourInfo.tsx
  src/components/layout/Navigation/index.tsx
  src/hooks/message/useGetMessage.ts
  src/hooks/message/useGetRoom.ts
  src/hooks/message/useMsgAPI.ts
  src/hooks/useAPI.ts
  src/pages/message.tsx
  src/pages/messageSend.tsx
  src/pages/messages/[roomId]/index.tsx
  src/pages/messages/index.tsx
  src/types/message/messageType.ts
  src/types/message/roomType.ts
  src/utils/betweenTime.ts
  src/utils/convertDate.ts
Labels: ✨ Feature, 📬 API

#52 Feat/36 admin page
  package-lock.json
  package.json
  public/admin/logo.svg
  public/admin/modal_close.svg
  public/admin/page_left.svg
  public/admin/page_right.svg
  src/api/admin/admin.ts
  src/api/axiosModule.ts
  src/atoms/admin/admin.ts
  src/components/admin/detail/contents.tsx
  src/components/admin/detail/modal.tsx
  src/components/admin/detail/profile.tsx
  src/components/admin/detail/reject.tsx
  src/components/admin/index/content.tsx
  src/components/admin/index/header.tsx
  src/components/admin/index/pageBtn.tsx
  src/components/admin/index/tabbar.tsx
  src/constants/admin.ts
  src/constants/version.ts
  src/hooks/admin/useGetAdminUserList.ts
  src/hooks/admin/usePostPermission.ts
  src/hooks/admin/usePostTemp.ts
  src/hooks/useAppVersion.ts
  src/pages/_app.tsx
  src/pages/admin/detail.tsx
  src/pages/admin/index.tsx
  src/types/admin/admin.d.ts
Labels: ✨ Feature, 📬 API

#54 My article page
  src/components/community/list/freeTab.tsx
  src/components/community/list/header.tsx
  src/components/community/list/interactTab.tsx
  src/pages/community/index.tsx
  src/pages/mypage/postList.tsx
Labels: ✨ Feature

#58 Fix/36 admin
  src/components/admin/detail/contents.tsx
  src/components/admin/detail/modal.tsx
  src/components/admin/detail/profile.tsx
  src/components/admin/index/content.tsx
  src/hooks/admin/useDetailDispatch.ts
  src/hooks/admin/useGetAdminUserList.ts
  src/pages/admin/detail.tsx
  src/pages/admin/index.tsx
Labels: ✨ Feature, 🔨 Refactor

#60 Feature/57 profile update
  public/mypage/cancel.png
  src/api/axiosModule.ts
  src/api/mypage/updateProfile.ts
  src/atoms/profileStateAtom.ts
  src/components/community/list/listCard.tsx
  src/components/mypage/countryImg.ts
  src/pages/mypage/edit/index.tsx
  src/pages/mypage/edit/nickname.tsx
  src/pages/mypage/index.tsx
  src/types/community/article.d.ts
  src/types/mypage/profileType.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#62 Fix/61 country code to server
  src/atoms/auth/signUpAtoms.ts
  src/components/authpage/signup/dropDownSignUpCountry.tsx
  src/types/countryList.ts
Labels: ✨ Feature, 📬 API

#65 Fix/36 admin
  src/components/admin/detail/profile.tsx
  src/components/admin/index/content.tsx
  src/hooks/admin/useGetAdminUserList.ts
  src/pages/admin/index.tsx
Labels: 🚂 Refactor

#67 [리팩토링] mypage
  src/components/community/detail/comment.tsx
  src/components/community/detail/profile.tsx
  src/components/community/list/listCard.tsx
  src/components/messageComp/msgList.tsx
  src/components/messageComp/yourInfo.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/countryImg.ts
  src/modules/utils.ts
  src/pages/mypage/edit/index.tsx
  src/pages/mypage/index.tsx
Labels: 🚂 Refactor

#69 Feature/68page routing
  src/hooks/useRedirectToMain.ts
  src/pages/_app.tsx
  src/pages/admin/index.tsx
Labels: ✨ Feature
